/var/spool/slurmd/job11708/slurm_script: line 18: module: command not found
2025-10-19 12:21:25.039055: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-19 12:21:25.070058: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-19 12:21:25.070091: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-19 12:21:25.070117: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-19 12:21:25.076087: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-19 12:21:25.076268: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-19 12:21:26.248372: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[12:21:28] 

****
Pre-condition Violation
no owner
Violation occurred on line 146 in file /home/conda/feedstock_root/build_artifacts/rdkit-meta_1732947292231/work/Code/GraphMol/Atom.h
Failed Expression: dp_mol
----------
Stacktrace:
 0# Invar::Invariant::toString[abi:cxx11]() const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libRDKitRDGeneral.so.1
 1# Invar::operator<<(std::ostream&, Invar::Invariant const&) in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libRDKitRDGeneral.so.1
 2# RDKit::Atom::getDegree() const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/../../../../libRDKitGraphMol.so.1
 3# 0x00007F75292B679A in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
 4# boost::python::objects::function::call(_object*, _object*) const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
 5# 0x00007F75297FD449 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
 6# boost::python::detail::exception_handler::operator()(boost::function_n<void> const&) const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
 7# 0x00007F75271BAB14 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdSLNParse.so
 8# 0x00007F7527627384 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdChemReactions.so
 9# 0x00007F75276273D4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdChemReactions.so
10# 0x00007F75277A7804 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdMolChemicalFeatures.so
11# 0x00007F75281ED174 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdDepictor.so
12# 0x00007F7528A8CCC4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdmolfiles.so
13# 0x00007F7528A8CD14 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdmolfiles.so
14# 0x00007F752EA46A24 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdCIPLabeler.so
15# 0x00007F75292FFDC4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
16# 0x00007F752929156D in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
17# 0x00007F752929108D in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
18# 0x00007F7529290BAD in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
19# 0x00007F75292906CD in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
20# 0x00007F75292901ED in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
21# 0x00007F75298BCA94 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
22# 0x00007F75298BCAE4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
23# 0x00007F75298BCB34 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
24# 0x00007F75298BCB84 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
25# boost::python::handle_exception_impl(boost::function_n<void>) in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
26# 0x00007F75297FA9B3 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
27# _PyObject_MakeTpCall in /home/ivanam/.conda/envs/bio_inf/bin/python
28# _PyEval_EvalFrameDefault in /home/ivanam/.conda/envs/bio_inf/bin/python
29# 0x000055ADE504142D in /home/ivanam/.conda/envs/bio_inf/bin/python
30# PyEval_EvalCode in /home/ivanam/.conda/envs/bio_inf/bin/python
31# 0x000055ADE505FA1A in /home/ivanam/.conda/envs/bio_inf/bin/python
32# 0x000055ADE505B593 in /home/ivanam/.conda/envs/bio_inf/bin/python
33# 0x000055ADE5070930 in /home/ivanam/.conda/envs/bio_inf/bin/python
34# _PyRun_SimpleFileObject in /home/ivanam/.conda/envs/bio_inf/bin/python
35# _PyRun_AnyFileObject in /home/ivanam/.conda/envs/bio_inf/bin/python
36# Py_RunMain in /home/ivanam/.conda/envs/bio_inf/bin/python
37# Py_BytesMain in /home/ivanam/.conda/envs/bio_inf/bin/python
38# 0x00007F758E7CD24A in /lib/x86_64-linux-gnu/libc.so.6
39# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
40# 0x000055ADE503091D in /home/ivanam/.conda/envs/bio_inf/bin/python
----------
****

2025-10-19 12:21:28.792713: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2211] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
/home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/spektral/data/utils.py:221: UserWarning: you are shuffling a 'MyDataset' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(a)
Traceback (most recent call last):
  File "/home/ivanam/BIO-Info/bio_info/multi_seminar2/training/gcn_train_multi.py", line 137, in <module>
    history = model.fit(
              ^^^^^^^^^^
  File "/home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ivanam/BIO-Info/bio_info/multi_seminar2/models/gcn.py", line 42, in call
    x = self.conv3([x, a])
        ^^^^^^^^^^
AttributeError: Exception encountered when calling layer 'gcn__multi_class' (type GCN_MultiClass).

'GCN_MultiClass' object has no attribute 'conv3'

Call arguments received by layer 'gcn__multi_class' (type GCN_MultiClass):
  • inputs=('tf.Tensor(shape=(32, 44, 12), dtype=float32)', 'tf.Tensor(shape=(32, 44, 44), dtype=float32)')
  • training=False
