/var/spool/slurmd/job11713/slurm_script: line 18: module: command not found
2025-10-19 12:45:42.507257: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-19 12:45:42.538326: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-19 12:45:42.538359: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-19 12:45:42.538386: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-19 12:45:42.544438: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-19 12:45:42.544615: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-19 12:45:43.733747: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[12:45:46] 

****
Pre-condition Violation
no owner
Violation occurred on line 146 in file /home/conda/feedstock_root/build_artifacts/rdkit-meta_1732947292231/work/Code/GraphMol/Atom.h
Failed Expression: dp_mol
----------
Stacktrace:
 0# Invar::Invariant::toString[abi:cxx11]() const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libRDKitRDGeneral.so.1
 1# Invar::operator<<(std::ostream&, Invar::Invariant const&) in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libRDKitRDGeneral.so.1
 2# RDKit::Atom::getDegree() const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/../../../../libRDKitGraphMol.so.1
 3# 0x00007FF85038179A in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
 4# boost::python::objects::function::call(_object*, _object*) const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
 5# 0x00007FF8509C8449 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
 6# boost::python::detail::exception_handler::operator()(boost::function_n<void> const&) const in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
 7# 0x00007FF84E28BB14 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdSLNParse.so
 8# 0x00007FF84E6F8384 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdChemReactions.so
 9# 0x00007FF84E6F83D4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdChemReactions.so
10# 0x00007FF84E878804 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdMolChemicalFeatures.so
11# 0x00007FF84F3AF174 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdDepictor.so
12# 0x00007FF84FB4ECC4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdmolfiles.so
13# 0x00007FF84FB4ED14 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdmolfiles.so
14# 0x00007FF84FC64A24 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdCIPLabeler.so
15# 0x00007FF8503CADC4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
16# 0x00007FF85035C56D in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
17# 0x00007FF85035C08D in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
18# 0x00007FF85035BBAD in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
19# 0x00007FF85035B6CD in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
20# 0x00007FF85035B1ED in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/Chem/rdchem.so
21# 0x00007FF850A87A94 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
22# 0x00007FF850A87AE4 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
23# 0x00007FF850A87B34 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
24# 0x00007FF850A87B84 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/rdBase.so
25# boost::python::handle_exception_impl(boost::function_n<void>) in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
26# 0x00007FF8509C59B3 in /home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/rdkit/../../../libboost_python311.so.1.86.0
27# _PyObject_MakeTpCall in /home/ivanam/.conda/envs/bio_inf/bin/python
28# _PyEval_EvalFrameDefault in /home/ivanam/.conda/envs/bio_inf/bin/python
29# 0x00005601D8B9042D in /home/ivanam/.conda/envs/bio_inf/bin/python
30# PyEval_EvalCode in /home/ivanam/.conda/envs/bio_inf/bin/python
31# 0x00005601D8BAEA1A in /home/ivanam/.conda/envs/bio_inf/bin/python
32# 0x00005601D8BAA593 in /home/ivanam/.conda/envs/bio_inf/bin/python
33# 0x00005601D8BBF930 in /home/ivanam/.conda/envs/bio_inf/bin/python
34# _PyRun_SimpleFileObject in /home/ivanam/.conda/envs/bio_inf/bin/python
35# _PyRun_AnyFileObject in /home/ivanam/.conda/envs/bio_inf/bin/python
36# Py_RunMain in /home/ivanam/.conda/envs/bio_inf/bin/python
37# Py_BytesMain in /home/ivanam/.conda/envs/bio_inf/bin/python
38# 0x00007FF8B589624A in /lib/x86_64-linux-gnu/libc.so.6
39# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
40# 0x00005601D8B7F91D in /home/ivanam/.conda/envs/bio_inf/bin/python
----------
****

2025-10-19 12:45:46.296673: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2211] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/home/ivanam/BIO-Info/bio_info/multi_seminar2/training/gcn_train_multi.py", line 30, in <module>
    tfds.count_labels(train_ds, 'Training')
  File "/home/ivanam/BIO-Info/bio_info/multi_seminar2/load_tfds_multi.py", line 38, in count_labels
    for _, label in dataset.as_numpy_iterator():
  File "/home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4691, in __next__
    return nest.map_structure(to_numpy, next(self._iterator))
                                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 809, in __next__
    return self._next_internal()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3028, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ivanam/.conda/envs/bio_inf/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 5888, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_11_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes at component 4: expected [2] but got [0]. [Op:IteratorGetNext] name: 
